config/routes.rb
Rails.application.routes.draw do
  resources :clinics
  devise_for :users, path: 'user'
  resources :patients, :users
  resources :doctors do
    resources :patients
  end
  
  root :to =>'pages#home'
  
  get '/appointment', to: 'pages#appointment'
  get '/profile', to: 'pages#profile'
  get '/add_patient', to: 'patients#add_patient_to_doctor'
  get '/search', to: 'search#index'
  get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
class Patient < ApplicationRecord
    belongs_to :doctor, optional: true
    validates :email, uniqueness: true
    validates :firstName, :lastName, :dob, :address, :phone, :symptom, presence: true
end

app/controllers/patients_controller.rb
require 'observer'
class PatientsController < ApplicationController
  include Observable
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_action :observer, only: [:create, :add_patient_to_doctor]
  before_action :authenticate_admin!, only: [:index, :add_patient_to_doctor]
  
  def authenticate_admin!
    unless current_user.admin || current_user.doctor
      flash[:notice] = "You do not have sufficient permissions"
      redirect_to root_path
    end
  end

  # GET /patients
  # GET /patients.json
  def index
    if params[:doctor_id] && (current_user.doctor || current_user.admin)
      @doctor = Doctor.find(params[:doctor_id])
      @patients = @doctor.patients
    else
      @patients = Patient.all
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    unless current_user.admin
      if current_user.email != @patient.email
        flash[:notice] = "You do not have sufficient permissions"
        redirect_to root_path
      end
    else
      if params[:doctor_id] && (current_user.doctor || current_user.admin)
        @doctor = Doctor.find(params[:doctor_id])
        @patient = @doctor.patients.find(params[:id])
      end
    end
  end

  # GET /patients/new
  def new
    if Patient.exists?(email: current_user.email)
      @email = @current_user.email
      @patient = Patient.find_by_email(@email)
      respond_to do |format|
        format.html { redirect_to @patient, notice: 'Patient record already exists for: ' + @email}
        format.json { render :show, status: :created, location: @patient }
      end
    else
      @patient = Patient.new
    end
  end

  # GET /patients/1/edit
  def edit
    unless current_user.admin
      if current_user.email != @patient.email
        flash[:notice] = "You do not have sufficient permissions"
        redirect_to root_path
      end
    end
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)
    if !User.exists?(email: patient_params[:email])
      respond_to do |format|
        format.html { redirect_to new_user_path, notice: 'Patient record cannot be created without associated User!' }
      end
    else
      set_category
      respond_to do |format|
        if @patient.save
          changed
          notify_observers(nil, @patient)
          format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
          format.json { render :show, status: :created, location: @patient }
        else
          format.html { render :new }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    @email = current_user.email
    @patient = Patient.find(params[:id])
    @patient_email = @patient.email
    set_category
    if @email == @patient.email || current_user.admin
      respond_to do |format|
        if @patient.update(patient_params)
          if User.find_by_email(@patient_email)
            @user = User.find_by_email(@patient_email)
            @user.skip_reconfirmation!
            @user.update(email: patient_params[:email])
          end
          format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
          format.json { render :show, status: :ok, location: @patient }
        else
          format.html { render :edit }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to @patient, notice: 'You do not have permissions to edit other patients!'}
        format.json { render :show, status: :created, location: @patient }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @email = current_user.email
    @patient = Patient.find(params[:id])
    
    if params[:doctor_id] && (current_user.doctor || current_user.admin)
      @doctor = Doctor.find(params[:doctor_id])
      @patient = @doctor.patients.find(params[:id])
      @doctor.patients.delete(@patient)
      
      respond_to do |format|
        format.html { redirect_to @doctor, notice: 'Patient was successfully removed.' }
        format.json { head :no_content }
      end
    elsif @email == @patient.email || current_user.admin
      @patient.destroy
      respond_to do |format|
        format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to @patient, notice: 'You do not have permissions to delete other patients!'}
        format.json { render :show, status: :created, location: @patient }
      end
    end
  end
  
  def add_patient_to_doctor
    @doctor = Doctor.find(params[:doctor_id])
    @patient_id = params[:patient_id]
    @patient = Patient.find(@patient_id)
    
    respond_to do |format|
      if @patient.save
        @doctor.patients << @patient
        changed
        notify_observers(@doctor, @patient)
        format.html { redirect_to @doctor, notice: 'Patient successfully added to Doctor.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def set_category
    @patient.category = AgeGroup.setAgeCategory(@patient.dob.to_s)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      if !Patient.exists?(params[:id])
        flash[:notice] = "Patient does not exist"
        redirect_to patients_path
      else
        @patient = Patient.find(params[:id])
      end
    end
    
    def observer
      add_observer(Notifier.new)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:firstName, :lastName, :email, :dob, :address, :phone, :symptom, :category)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="field">
      <%= form.label :firstName %>
      <%= form.text_field :firstName, id: :patient_firstName, class: ['form-control'] %>
    </div>
    
    <div class="field">
      <%= form.label :lastName %>
      <%= form.text_field :lastName, id: :patient_lastName, class: ['form-control'] %>
    </div>
    
    <div class="field">
      <%= form.label :email %>
      <% if current_user.doctor || current_user.admin %>
        <%= form.text_field :email, id: :patient_email, class: ['form-control'] %>
      <% else %>
        <%= form.text_field :email, id: :patient_email, :value => current_user.email, class: ['form-control'] %>
      <% end %>
    </div>
  
    <div class="field">
      <%= form.label :dob %>
      <%= form.date_select :dob, :order => [:day, :month, :year], :start_year=> 1900, :end_year=> Date.current.year, id: :patient_dob, :value => current_user.dob, class: ['form-control'] %>
    </div>
  
    <div class="field">
      <%= form.label :address %>
      <%= form.text_field :address, id: :patient_address, class: ['form-control'] %>
    </div>
  
    <div class="field">
      <%= form.label :phone %>
      <%= form.number_field :phone, id: :patient_phone, class: ['form-control'] %>
    </div>
  
    <div class="field">
      <%= form.label :symptom %>
      <%= form.text_field :symptom, id: :patient_symptom, class: ['form-control'] %>
    </div>

    </br>
    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1 class="headings">Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1 class="headings">Patients</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Dob</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Symptom</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.firstName %></td>
        <td><%= patient.lastName %></td>
        <td><%= patient.email %></td>
        <td><%= patient.dob %></td>
        <td><%= patient.address %></td>
        <td><%= patient.phone %></td>
        <td><%= patient.symptom %></td>
        <td><%= patient.category %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if params[:id] %>
          <td><%= link_to 'Add Patient to Doctor', add_patient_path(:patient_id => patient, :doctor_id => params[:id]) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

<div class="col-md-5 col-centered">
  <%= pie_chart Patient.group(:category).count, donut: true %>
</div>

app/views/patients/new.html.erb
<h1 class="headings">New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<h1 class="headings">Patient</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Dob</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Symptom</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @patient.firstName %></td>
      <td><%= @patient.lastName %></td>
      <td><%= @patient.email %></td>
      <td><%= @patient.dob %></td>
      <td><%= @patient.address %></td>
      <td><%= @patient.phone %></td>
      <td><%= @patient.symptom %></td>
      <td><%= @patient.category %></td>
    </tr>
  </tbody>
</table>

<% if @patient.doctor %>
  <h1 class="headings">Doctor</h1>
  
  <table class="table table-hover">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Clinic</th>
        <th>Specialisation</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @doctor = @patient.doctor %>
        <tr>
          <td><%= @doctor.firstName %></td>
          <td><%= @doctor.lastName %></td>
          <td><%= @doctor.email %></td>
          <td><%= @doctor.clinic %></td>
          <td><%= @doctor.specialisation %></td>
        </tr>
    </tbody>
  </table>
<% end %>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>