config/routes.rb
Rails.application.routes.draw do
  resources :clinics
  devise_for :users, path: 'user'
  resources :patients, :users
  resources :doctors do
    resources :patients
  end
  
  root :to =>'pages#home'
  
  get '/appointment', to: 'pages#appointment'
  get '/profile', to: 'pages#profile'
  get '/add_patient', to: 'patients#add_patient_to_doctor'
  get '/search', to: 'search#index'
  get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :patients
    validates :email, presence: true, uniqueness: true
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:index, :new, :create, :destroy]
  
  def authenticate_admin!
    unless current_user.admin
      flash[:notice] = "You do not have sufficient permissions"
      redirect_to root_path
    end
  end
  
  def index
    @doctors = Doctor.all
  end

  def show
    unless current_user.admin
      if current_user.email != @doctor.email
        flash[:notice] = "You do not have sufficient permissions"
        redirect_to root_path
      end
    else
      if params[:doctor_id] && (current_user.doctor || current_user.admin)
        @doctor = Doctor.find(params[:doctor_id])
      end
    end
  end
  
  def new
    @doctor = Doctor.new
    @clinics = Clinic.all
    create_list(@clinics)
  end

  def edit
    unless current_user.admin
      if current_user.email != @doctor.email
        flash[:notice] = "You do not have sufficient permissions"
        redirect_to root_path
      end
    else
      @doctor = Doctor.find(params[:id])
      if @doctor.email == current_user.email || current_user.admin
        @clinics = Clinic.all
        create_list(@clinics)
      end
    end
  end
  
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @email = @doctor.email
    @doctor = Doctor.find(params[:id])
    @doc_email = @doctor.email
    if @email == @doctor.email || current_user.admin
      respond_to do |format|
        if @doctor.update(doctor_params)
          if User.find_by_email(@doc_email)
            @user = User.find_by_email(@doc_email)
            @user.skip_reconfirmation!
            @user.update(email: doctor_params[:email])
          end
          format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
          format.json { render :show, status: :ok, location: @doctor }
        else
          format.html { render :edit }
          format.json { render json: @doctor.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to @patient, notice: 'You do not have permissions to edit other doctors!'}
        format.json { render :show, status: :created, location: @patient }
      end
    end
  end
  
  def destroy
    @doctor.destroy
      respond_to do |format|
        format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
        format.json { head :no_content }
      end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      if !Doctor.exists?(params[:id])
        flash[:notice] = "Doctor does not exist"
        redirect_to doctors_path
      else
        @doctor = Doctor.find(params[:id])
      end
    end
    
    def create_list(clinics)
      @options = []
      clinics.each do |clinic|
        @options.push(clinic.name)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:firstName, :lastName, :email, :clinic, :specialisation)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="field">
      <%= form.label :firstName %>
      <%= form.text_field :firstName, id: :doctor_firstName, class: ['form-control'] %>
    </div>
    
    <div class="field">
      <%= form.label :lastName %>
      <%= form.text_field :lastName, id: :doctor_lastName, class: ['form-control'] %>
    </div>
    
    <div class="field">
      <%= form.label :email %><br />
      <% if current_user.admin %>
        <%= form.email_field :email, id: :doctor_email, autofocus: true, autocomplete: "email", class: ['form-control'] %>
      <% else %>
        <%= form.email_field :email, id: :doctor_email, autofocus: true, autocomplete: "email", class: ['form-control'] %>
      <% end %>
    </div>
    
    <div class="field">
      <%= form.label :clinic %>
      <%= form.select :clinic, @options.map { |value| [ value, value ] }, {}, {class: ['form-control']} %>
    </div>
  
    <div class="field">
      <%= form.label :specialisation %>
      <%= form.text_field :specialisation, id: :doctor_specialisation, class: ['form-control'] %>
    </div>
    
    </br>
    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1 class="headings">Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<h1 class="headings">Doctors</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Clinic</th>
      <th>Specialisation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.firstName %></td>
        <td><%= doctor.lastName %></td>
        <td><%= doctor.email %></td>
        <td><%= doctor.clinic %></td>
        <td><%= doctor.specialisation %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1 class="headings">New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<h1 class="headings">Doctor</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Clinic</th>
      <th>Specialisation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @doctor.firstName %></td>
      <td><%= @doctor.lastName %></td>
      <td><%= @doctor.email %></td>
      <td><%= @doctor.clinic %></td>
      <td><%= @doctor.specialisation %></td>
    </tr>
  </tbody>
</table>

<h2 class="headings">Patients</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Dob</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Symptom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctor.patients.each do |patient| %>
      <tr>
        <td><%= patient.firstName %></td>
        <td><%= patient.lastName %></td>
        <td><%= patient.email %></td>
        <td><%= patient.dob %></td>
        <td><%= patient.address %></td>
        <td><%= patient.phone %></td>
        <td><%= patient.symptom %></td>
        <td><%= patient.category %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Remove', doctor_patient_url(:id => patient, :doctor_id => @doctor.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %> |
<%= link_to 'Show Patients', doctor_patients_path(@doctor) %> |
<%= link_to 'Add Patients', patients_path(:id => @doctor.id) %>

<div class="col-md-5 col-centered">
  <%= pie_chart @doctor.patients.group(:category).count, donut: true %>
</div>