config/routes.rb
Rails.application.routes.draw do
  resources :clinics
  devise_for :users, path: 'user'
  resources :patients, :users
  resources :doctors do
    resources :patients
  end
  
  root :to =>'pages#home'
  
  get '/appointment', to: 'pages#appointment'
  get '/profile', to: 'pages#profile'
  get '/add_patient', to: 'patients#add_patient_to_doctor'
  get '/search', to: 'search#index'
  get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer id='footer'>
    &copy;<%= Time.now.year %> HealthApp
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="header">
  <h2>
    <li class="nav-item nav-link">
      <%= link_to 'HealthApp', root_path %>
    </li>
  </h2>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item nav-link">
        <%= link_to 'Home', root_path %>
      </li>
      <li class="nav-item nav-link">
        <%= link_to 'Make Appointment', appointment_path %>
      </li>
      <% if user_signed_in? %>
        <% if current_user.doctor %>
          <li class="nav-item nav-link">
            <%= link_to 'Manage Patients', doctor_patients_path(:doctor_id => Doctor.find_by_email(current_user.email).id) %>
          </li>
        <% elsif current_user.admin %>
          <li class="nav-item nav-link">
            <%= link_to 'Manage Patients', patients_path %>
          </li>
          <li class="nav-item nav-link">
            <%= link_to 'Manage Doctors', doctors_path %>
          </li>
          <li class="nav-item nav-link">
            <%= link_to 'Manage Users', users_path %>
          </li>
        <% end %>
          <li class="nav-item nav-link">
            <%= link_to 'Profile: ' + current_user.email, profile_path %>
          </li>
          <li class="nav-item nav-link">
            <%= link_to 'Sign Out', destroy_user_session_path, :method =>:delete %>
          </li>
      <% else %>
        <li class="nav-item nav-link">
          <%= link_to 'Register', new_user_registration_path %>
        </li>
        <li class="nav-item nav-link">
          <%= link_to 'Sign In', new_user_session_path %>
        </li>
      <% end %>
    </ul>
    <% if user_signed_in? %>
      <% if current_user.admin %>
        <div class="search">
          <%= form_tag(search_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search" %>
            <%= submit_tag "Search", :name => nil %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthApp</title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body class='container-fluid'>
    <%= render 'layouts/header' %>
    <hr>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <hr>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/appointment.html.erb
<h1>Hi <%= @patient.email %></h1>
<p>You have recently created an appointment.</p>
<p>You can view and update any information here: <a href="https://whispering-scrubland-72575.herokuapp.com/patients/<%= @patient.id %>">here</a></p>
<p>You will be notified again when you have been assigned a doctor.</p>

app/views/layouts/doctor_notification.html.erb
<h1>Hi <%= @doctor.email %></h1>
<p>A new patient has been added to your schedule</p>
<p>View your patients: <a href="https://whispering-scrubland-72575.herokuapp.com/doctors/<%= @doctor.id %>/patients">here</a></p>

app/views/layouts/notification.html.erb
<h1>Hi <%= @doctor.email %></h1>
<p>A new patient has been added to your schedule</p>
<p>View your patients: <a href="https://whispering-scrubland-72575.herokuapp.com/doctors/<%= @doctor.id %>/patients">here</a></p>

app/views/layouts/patient_notification.html.erb
<h1>Hi <%= @patient.email %></h1>
<p>A doctor has been assigned to you regarding your appointment</p>
<p>You can view all details here: <a href="https://whispering-scrubland-72575.herokuapp.com/patients/<%= @patient.id %>">here</a></p>